support openethereum/geth metrics
netdata/go.d.plugin pull request #580
Opened 2021-06-02 14:53 UTC by OdysLam

Tested :)

2021-06-04 13:30 UTC, thiagoftsm commented on config/go.d/prometheus.conf
> +
@OdysLam , please, add a new line at the end of this file.

2021-06-08 08:26 UTC, ilyam8 requested changes

2021-06-08 12:14 UTC, OdysLam commented
@ilyam8 the metrics don't have a prefix tied to the application, so I left it as-is

2021-06-08 14:32 UTC, ilyam8 approved these changes

2021-06-08 14:43 UTC, merged